kind: Service
apiVersion: v1
metadata:
  name: bus-schedule-service
spec:
  type: NodePort
  selector:
    app: bus-schedule
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-schedule-deployment
  labels:
    app: bus-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus-schedule
  template:
    metadata:
      labels:
        app: bus-schedule
    spec:
      containers:
      - name: bus-schedule
        image: nginx
        ports:
        - containerPort: 80
