kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31297

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: train-schedule
  name: train-schedule-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: train-schedule
  template: 
    metadata: 
      labels: 
        app: train-schedule
    spec: 
      containers: 
         -image: nginx
          name: train-schedule
          ports:
            - containerPort: 80
          resources: 
            limits: 
              cpu: 2
              memory: 2Gi
            requests: 
              cpu: 1
              memory: 1Gi
